// ============================================================
// Provider Presets — Pure data, no server-side imports
// Safe to import from client-side components
// ============================================================

export type AiCategory = 'llm' | 'image' | 'video' | 'tts'

export interface ModelOption {
  id: string       // Model identifier used in API calls
  name: string     // Display name
  tags?: string[]  // Tags like '推荐', '免费', '快速', '最新'
}

export interface ProviderPreset {
  provider: string
  name: string
  defaultBaseUrl: string
  defaultModel: string
  description: string
  envKey: string // env var name for API key fallback
  availableModels?: ModelOption[] // Selectable models for this provider
}

export const PROVIDER_PRESETS: Record<AiCategory, ProviderPreset[]> = {
  llm: [
    {
      provider: 'nvidia',
      name: 'NVIDIA NIM',
      defaultBaseUrl: 'https://integrate.api.nvidia.com/v1',
      defaultModel: 'z-ai/glm-5.1',
      description: 'NVIDIA NIM API — GLM5.1, DeepSeek V4, MiniMax, Llama, Qwen 等 70+ 模型',
      envKey: 'NVIDIA_API_KEY',
      availableModels: [
        { id: 'z-ai/glm-5.1', name: 'GLM-5.1', tags: ['推荐', '最新'] },
        { id: 'z-ai/glm5', name: 'GLM-5' },
        { id: 'z-ai/glm4.7', name: 'GLM-4.7' },
        { id: 'deepseek-ai/deepseek-v4-pro', name: 'DeepSeek V4 Pro', tags: ['推荐', '最新'] },
        { id: 'deepseek-ai/deepseek-v4-flash', name: 'DeepSeek V4 Flash', tags: ['快速'] },
        { id: 'deepseek-ai/deepseek-v3.2', name: 'DeepSeek V3.2' },
        { id: 'deepseek-ai/deepseek-v3.1-terminus', name: 'DeepSeek V3.1 Terminus' },
        { id: 'minimaxai/minimax-m2.7', name: 'MiniMax M2.7', tags: ['最新'] },
        { id: 'minimaxai/minimax-m2.5', name: 'MiniMax M2.5' },
        { id: 'qwen/qwen3.5-397b-a17b', name: 'Qwen 3.5 397B', tags: ['推荐', '最新'] },
        { id: 'qwen/qwen3.5-122b-a10b', name: 'Qwen 3.5 122B' },
        { id: 'qwen/qwen3-next-80b-a3b-instruct', name: 'Qwen 3 Next 80B' },
        { id: 'qwen/qwen3-next-80b-a3b-thinking', name: 'Qwen 3 Next Thinking 80B', tags: ['推理'] },
        { id: 'moonshotai/kimi-k2.5', name: 'Kimi K2.5', tags: ['最新'] },
        { id: 'moonshotai/kimi-k2-instruct', name: 'Kimi K2' },
        { id: 'moonshotai/kimi-k2-thinking', name: 'Kimi K2 Thinking', tags: ['推理'] },
        { id: 'meta/llama-4-maverick-17b-128e-instruct', name: 'Llama 4 Maverick', tags: ['最新'] },
        { id: 'meta/llama-3.3-70b-instruct', name: 'Llama 3.3 70B' },
        { id: 'meta/llama-3.1-405b-instruct', name: 'Llama 3.1 405B' },
        { id: 'meta/llama-3.1-70b-instruct', name: 'Llama 3.1 70B' },
        { id: 'meta/llama-3.1-8b-instruct', name: 'Llama 3.1 8B', tags: ['快速'] },
        { id: 'nvidia/llama-3.1-nemotron-ultra-253b-v1', name: 'Nemotron Ultra 253B', tags: ['推荐'] },
        { id: 'nvidia/llama-3.1-nemotron-70b-instruct', name: 'Nemotron 70B' },
        { id: 'nvidia/llama-3.3-nemotron-super-49b-v1.5', name: 'Nemotron Super 49B v1.5' },
        { id: 'mistralai/mistral-large-3-675b-instruct-2512', name: 'Mistral Large 3 675B', tags: ['最新'] },
        { id: 'mistralai/mistral-medium-3-instruct', name: 'Mistral Medium 3' },
        { id: 'mistralai/mistral-small-4-119b-2603', name: 'Mistral Small 4' },
        { id: 'mistralai/mixtral-8x22b-instruct-v0.1', name: 'Mixtral 8x22B' },
        { id: 'openai/gpt-oss-120b', name: 'GPT-OSS 120B' },
        { id: '01-ai/yi-large', name: 'Yi Large' },
        { id: 'bytedance/seed-oss-36b-instruct', name: 'Seed OSS 36B' },
      ],
    },
    {
      provider: 'openai',
      name: 'OpenAI',
      defaultBaseUrl: 'https://api.openai.com/v1',
      defaultModel: 'gpt-4o',
      description: 'OpenAI GPT-4o / GPT-4o-mini',
      envKey: 'OPENAI_API_KEY',
      availableModels: [
        { id: 'gpt-4o', name: 'GPT-4o', tags: ['推荐'] },
        { id: 'gpt-4o-mini', name: 'GPT-4o Mini', tags: ['快速', '经济'] },
        { id: 'gpt-4.1', name: 'GPT-4.1', tags: ['最新'] },
        { id: 'gpt-4.1-mini', name: 'GPT-4.1 Mini', tags: ['快速'] },
        { id: 'gpt-4.1-nano', name: 'GPT-4.1 Nano', tags: ['经济'] },
        { id: 'o3', name: 'o3', tags: ['推理'] },
        { id: 'o4-mini', name: 'o4-mini', tags: ['推理', '经济'] },
      ],
    },
    {
      provider: 'siliconflow',
      name: 'SiliconFlow',
      defaultBaseUrl: 'https://api.siliconflow.cn/v1',
      defaultModel: 'deepseek-ai/DeepSeek-V3',
      description: 'SiliconFlow — DeepSeek, Qwen, Llama',
      envKey: 'SILICONFLOW_API_KEY',
      availableModels: [
        { id: 'deepseek-ai/DeepSeek-V3', name: 'DeepSeek V3', tags: ['推荐'] },
        { id: 'deepseek-ai/DeepSeek-R1', name: 'DeepSeek R1', tags: ['推理'] },
        { id: 'Qwen/Qwen2.5-72B-Instruct', name: 'Qwen 2.5 72B' },
        { id: 'Qwen/Qwen2.5-32B-Instruct', name: 'Qwen 2.5 32B' },
        { id: 'meta-llama/Meta-Llama-3.1-70B-Instruct', name: 'Llama 3.1 70B' },
        { id: 'meta-llama/Meta-Llama-3.1-8B-Instruct', name: 'Llama 3.1 8B', tags: ['快速'] },
      ],
    },
    {
      provider: 'deepseek',
      name: 'DeepSeek',
      defaultBaseUrl: 'https://api.deepseek.com/v1',
      defaultModel: 'deepseek-chat',
      description: 'DeepSeek official API',
      envKey: 'DEEPSEEK_API_KEY',
      availableModels: [
        { id: 'deepseek-chat', name: 'DeepSeek Chat', tags: ['推荐'] },
        { id: 'deepseek-reasoner', name: 'DeepSeek Reasoner', tags: ['推理'] },
      ],
    },
    {
      provider: 'sensenova',
      name: '商汤 SenseNova',
      defaultBaseUrl: 'https://token.sensenova.cn/v1',
      defaultModel: 'deepseek-v4-flash',
      description: '商汤日日新大模型平台 — DeepSeek V4 Flash 限时免费，支持 function calling，OpenAI 兼容接口',
      envKey: 'sensenova_key',
      availableModels: [
        { id: 'deepseek-v4-flash', name: 'DeepSeek V4 Flash', tags: ['免费', '推荐', '最新'] },
        { id: 'SenseChat-5', name: 'SenseChat-5', tags: ['推荐'] },
        { id: 'SenseChat-5-Pro', name: 'SenseChat-5 Pro', tags: ['高级'] },
        { id: 'DeepSeek-V3', name: 'DeepSeek V3' },
        { id: 'Qwen3-235B-A22B', name: 'Qwen3 235B' },
        { id: 'Qwen3-30B-A3B', name: 'Qwen3 30B', tags: ['快速'] },
      ],
    },
    {
      provider: 'openrouter',
      name: 'OpenRouter',
      defaultBaseUrl: 'https://openrouter.ai/api/v1',
      defaultModel: 'deepseek/deepseek-v4-flash:free',
      description: 'OpenRouter — 聚合 300+ 模型，支持免费模型，一个 Key 访问所有主流 LLM',
      envKey: 'OPENROUTER_API_KEY',
      availableModels: [
        // ── 免费模型 ──
        { id: 'deepseek/deepseek-v4-flash:free', name: 'DeepSeek V4 Flash (免费)', tags: ['免费', '推荐', '最新'] },
        { id: 'qwen/qwen3-coder-480b-a35b-07-25:free', name: 'Qwen3 Coder 480B (免费)', tags: ['免费', '最新'] },
        { id: 'qwen/qwen3-next-80b-a3b-instruct-2509:free', name: 'Qwen3 Next 80B (免费)', tags: ['免费'] },
        { id: 'meta-llama/llama-3.3-70b-instruct:free', name: 'Llama 3.3 70B (免费)', tags: ['免费'] },
        { id: 'nvidia/nemotron-3-super-120b-a12b:free', name: 'Nemotron 3 Super 120B (免费)', tags: ['免费'] },
        { id: 'nousresearch/hermes-3-llama-3.1-405b:free', name: 'Hermes 3 405B (免费)', tags: ['免费'] },
        { id: 'openai/gpt-oss-120b:free', name: 'GPT-OSS 120B (免费)', tags: ['免费'] },
        { id: 'openai/gpt-oss-20b:free', name: 'GPT-OSS 20B (免费)', tags: ['免费', '快速'] },
        { id: 'google/gemma-4-31b-it:free', name: 'Gemma 4 31B (免费)', tags: ['免费', '最新'] },
        { id: 'google/gemma-4-26b-a4b-it-20260403:free', name: 'Gemma 4 26B A4B (免费)', tags: ['免费', '最新'] },
        { id: 'minimax/minimax-m2.5:free', name: 'MiniMax M2.5 (免费)', tags: ['免费'] },
        { id: 'z-ai/glm-4.5-air:free', name: 'GLM 4.5 Air (免费)', tags: ['免费'] },
        { id: 'arcee-ai/trinity-large-thinking:free', name: 'Trinity Large Thinking (免费)', tags: ['免费', '推理'] },
        { id: 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free', name: 'Nemotron 3 Nano Omni (免费)', tags: ['免费', '推理'] },
        { id: 'baidu/cobuddy:free', name: '百度 CoBuddy (免费)', tags: ['免费'] },
        { id: 'poolside/laguna-m.1:free', name: 'Laguna M.1 (免费)', tags: ['免费'] },
        { id: 'poolside/laguna-xs.2:free', name: 'Laguna XS.2 (免费)', tags: ['免费', '快速'] },
        { id: 'nvidia/nemotron-nano-9b-v2:free', name: 'Nemotron Nano 9B (免费)', tags: ['免费', '快速'] },
        { id: 'nvidia/nemotron-3-nano-30b-a3b:free', name: 'Nemotron 3 Nano 30B (免费)', tags: ['免费', '快速'] },
        { id: 'meta-llama/llama-3.2-3b-instruct:free', name: 'Llama 3.2 3B (免费)', tags: ['免费', '快速'] },
        { id: 'liquid/lfm-2.5-1.2b-instruct-20260120:free', name: 'LFM 2.5 1.2B (免费)', tags: ['免费', '快速'] },
        { id: 'liquid/lfm-2.5-1.2b-thinking-20260120:free', name: 'LFM 2.5 1.2B Thinking (免费)', tags: ['免费', '推理'] },
        { id: 'venice/uncensored:free', name: 'Venice Uncensored (免费)', tags: ['免费'] },
        // ── 付费 - 高端 ──
        { id: 'anthropic/claude-sonnet-4', name: 'Claude Sonnet 4', tags: ['推荐', '最新'] },
        { id: 'anthropic/claude-opus-4', name: 'Claude Opus 4', tags: ['推理', '最强'] },
        { id: 'openai/gpt-4.1', name: 'GPT-4.1', tags: ['最新'] },
        { id: 'openai/o3', name: 'o3', tags: ['推理'] },
        { id: 'openai/o4-mini', name: 'o4-mini', tags: ['推理', '经济'] },
        { id: 'google/gemini-2.5-pro-preview', name: 'Gemini 2.5 Pro', tags: ['推荐', '最新'] },
        { id: 'google/gemini-2.5-flash-preview', name: 'Gemini 2.5 Flash', tags: ['快速'] },
        // ── 付费 - 国产 ──
        { id: 'deepseek/deepseek-chat-v3-0324', name: 'DeepSeek V3', tags: ['经济'] },
        { id: 'deepseek/deepseek-r1', name: 'DeepSeek R1', tags: ['推理'] },
        { id: 'qwen/qwen3-235b-a22b', name: 'Qwen3 235B', tags: ['经济'] },
        { id: 'qwen/qwen3-30b-a3b', name: 'Qwen3 30B', tags: ['经济', '快速'] },
        // ── 付费 - 开源 ──
        { id: 'meta-llama/llama-4-maverick', name: 'Llama 4 Maverick', tags: ['最新'] },
        { id: 'meta-llama/llama-3.3-70b-instruct', name: 'Llama 3.3 70B' },
        { id: 'mistralai/mistral-large-2411', name: 'Mistral Large' },
        { id: 'mistralai/mistral-small-3.1-24b-instruct', name: 'Mistral Small 3.1', tags: ['快速'] },
      ],
    },
    {
      provider: 'custom',
      name: '自定义 OpenAI 兼容',
      defaultBaseUrl: '',
      defaultModel: '',
      description: '任何 OpenAI 兼容接口（中转站、私有部署等）',
      envKey: 'CUSTOM_LLM_API_KEY',
    },
  ],
  image: [
    {
      provider: 'openai',
      name: 'OpenAI',
      defaultBaseUrl: 'https://api.openai.com/v1',
      defaultModel: 'gpt-image-1',
      description: 'OpenAI 图片生成 — 只需提供 API Key 即可使用',
      envKey: 'OPENAI_API_KEY',
      availableModels: [
        { id: 'gpt-image-1', name: 'GPT Image 1', tags: ['推荐', '最新'] },
        { id: 'dall-e-3', name: 'DALL·E 3' },
      ],
    },
    {
      provider: 'chatfire',
      name: 'Chatfire 统一网关',
      defaultBaseUrl: 'https://api.chatfire.site',
      defaultModel: 'gemini-3-pro-image-preview',
      description: 'Chatfire 统一网关 — 一个Key代理 Gemini/Seedream/OpenAI/MiniMax，国内可用',
      envKey: 'CHATFIRE_API_KEY',
      availableModels: [
        { id: 'gemini-3-pro-image-preview', name: 'Gemini 3 Pro Image', tags: ['推荐', '最新'] },
        { id: 'gemini-3.1-flash-image-preview', name: 'Gemini 3.1 Flash Image', tags: ['最新', '快速'] },
        { id: 'imagen-4.0-generate-001', name: 'Imagen 4.0', tags: ['最新'] },
        { id: 'imagen-4.0-fast-generate-001', name: 'Imagen 4.0 Fast', tags: ['快速'] },
        { id: 'gemini-2.5-flash-preview-image-generation', name: 'Gemini 2.5 Flash Image' },
        { id: 'doubao-seedream-5-0-260128', name: 'Seedream 5.0 (Chatfire代理)', tags: ['最新'] },
        { id: 'doubao-seedream-4-5-251128', name: 'Seedream 4.5 (Chatfire代理)' },
        { id: 'gpt-image-1', name: 'GPT Image 1' },
        { id: 'dall-e-3', name: 'DALL·E 3' },
        { id: 'MiniMax-Image-01', name: 'MiniMax Image 01' },
      ],
    },
    {
      provider: 'gemini',
      name: 'Google Gemini / Imagen',
      defaultBaseUrl: 'https://generativelanguage.googleapis.com',
      defaultModel: 'gemini-3-pro-image-preview',
      description: 'Google Gemini + Imagen 图片生成 — 只需提供 API Key 即可使用',
      envKey: 'GEMINI_API_KEY',
      availableModels: [
        { id: 'gemini-3-pro-image-preview', name: 'Gemini 3 Pro Image', tags: ['推荐', '最新'] },
        { id: 'gemini-3.1-flash-image-preview', name: 'Gemini 3.1 Flash Image', tags: ['最新', '快速'] },
        { id: 'imagen-4.0-ultra-generate-001', name: 'Imagen 4.0 Ultra', tags: ['高清'] },
        { id: 'imagen-4.0-generate-001', name: 'Imagen 4.0' },
        { id: 'imagen-4.0-fast-generate-001', name: 'Imagen 4.0 Fast', tags: ['快速'] },
        { id: 'gemini-2.5-flash-preview-image-generation', name: 'Gemini 2.5 Flash Image' },
        { id: 'gemini-2.0-flash-exp-image-generation', name: 'Gemini 2.0 Flash Image' },
      ],
    },
    {
      provider: 'minimax',
      name: 'MiniMax',
      defaultBaseUrl: 'https://api.minimax.chat',
      defaultModel: 'MiniMax-Image-01',
      description: 'MiniMax 图片生成 — 只需提供 API Key 即可使用，支持参考图',
      envKey: 'MINIMAX_API_KEY',
      availableModels: [
        { id: 'MiniMax-Image-01', name: 'MiniMax Image 01', tags: ['推荐'] },
      ],
    },
    {
      provider: 'volcengine',
      name: '火山引擎 Seedream',
      defaultBaseUrl: 'https://visual.volcengineapi.com',
      defaultModel: 'doubao-seedream-5-0-260128',
      description: '火山引擎 Seedream 图片生成 — 只需提供 API Key 即可使用',
      envKey: 'VOLCENGINE_API_KEY',
      availableModels: [
        { id: 'doubao-seedream-5-0-260128', name: 'Seedream 5.0', tags: ['推荐', '最新'] },
        { id: 'doubao-seedream-4-5-251128', name: 'Seedream 4.5' },
        { id: 'doubao-seedream-4-0-250828', name: 'Seedream 4.0' },
      ],
    },
    {
      provider: 'ali',
      name: '阿里百炼 万相',
      defaultBaseUrl: 'https://dashscope.aliyuncs.com',
      defaultModel: 'wan2.7-image-pro',
      description: '阿里百炼万相图片生成 — 只需提供 API Key 即可使用',
      envKey: 'ALI_API_KEY',
      availableModels: [
        { id: 'wan2.7-image-pro', name: '万相 2.7 Pro', tags: ['推荐', '最新'] },
        { id: 'wan2.7-image', name: '万相 2.7' },
        { id: 'wan2.6-t2i', name: '万相 2.6' },
        { id: 'wan2.5-t2i-preview', name: '万相 2.5 Preview' },
        { id: 'wan2.2-t2i-plus', name: '万相 2.2 Plus' },
        { id: 'wan2.2-t2i-flash', name: '万相 2.2 Flash', tags: ['快速'] },
        { id: 'wanx2.1-t2i-turbo', name: '万相 2.1 Turbo', tags: ['快速'] },
        { id: 'wanx2.1-t2i-plus', name: '万相 2.1 Plus' },
        { id: 'flux-dev', name: 'FLUX Dev' },
        { id: 'flux-schnell', name: 'FLUX Schnell', tags: ['快速'] },
      ],
    },
    {
      provider: 'custom',
      name: '自定义图片接口',
      defaultBaseUrl: '',
      defaultModel: '',
      description: '自定义 OpenAI 兼容图片生成接口',
      envKey: 'CUSTOM_IMAGE_API_KEY',
    },
  ],
  video: [
    {
      provider: 'minimax',
      name: 'MiniMax 海螺 AI',
      defaultBaseUrl: 'https://api.minimax.chat',
      defaultModel: 'minimax-hailuo-2.3',
      description: 'MiniMax 海螺 AI 视频生成 — 只需提供 API Key 即可使用',
      envKey: 'MINIMAX_API_KEY',
      availableModels: [
        { id: 'minimax-hailuo-2.3', name: '海螺 2.3', tags: ['推荐', '最新'] },
        { id: 'minimax-hailuo-2.3-fast', name: '海螺 2.3 Fast', tags: ['最新', '快速'] },
        { id: 'minimax-hailuo-02', name: '海螺 02' },
        { id: 't2v-01', name: 'T2V-01 文生视频' },
        { id: 't2v-01-director', name: 'T2V-01 Director 导演模式', tags: ['专业'] },
      ],
    },
    {
      provider: 'volcengine',
      name: '火山引擎 Seedance',
      defaultBaseUrl: 'https://visual.volcengineapi.com',
      defaultModel: 'doubao-seedance-2-0-260128',
      description: '火山引擎 Seedance 视频生成 — 只需提供 API Key 即可使用',
      envKey: 'VOLCENGINE_API_KEY',
      availableModels: [
        { id: 'doubao-seedance-2-0-260128', name: 'Seedance 2.0', tags: ['推荐', '最新'] },
        { id: 'doubao-seedance-2-0-fast-260128', name: 'Seedance 2.0 Fast', tags: ['最新', '快速'] },
        { id: 'doubao-seedance-1-5-pro-251215', name: 'Seedance 1.5 Pro' },
        { id: 'doubao-seedance-1-0-pro-250528', name: 'Seedance 1.0 Pro' },
        { id: 'doubao-seedance-1-0-lite-i2v-250428', name: 'Seedance 1.0 Lite I2V', tags: ['快速'] },
      ],
    },
    {
      provider: 'vidu',
      name: 'Vidu',
      defaultBaseUrl: 'https://api.vidu.cn',
      defaultModel: 'viduq3-pro',
      description: 'Vidu 视频生成 — 只需提供 API Key 即可使用',
      envKey: 'VIDU_API_KEY',
      availableModels: [
        { id: 'viduq3-pro', name: 'Vidu Q3 Pro', tags: ['推荐', '最新'] },
        { id: 'vidu2.0', name: 'Vidu 2.0' },
        { id: 'viduq2-pro-fast', name: 'Vidu Q2 Pro Fast', tags: ['快速'] },
        { id: 'viduq2-pro', name: 'Vidu Q2 Pro' },
        { id: 'viduq2-turbo', name: 'Vidu Q2 Turbo', tags: ['快速'] },
        { id: 'viduq1', name: 'Vidu Q1' },
      ],
    },
    {
      provider: 'ali',
      name: '阿里百炼 万相视频',
      defaultBaseUrl: 'https://dashscope.aliyuncs.com',
      defaultModel: 'wan2.7-i2v',
      description: '阿里百炼万相视频生成 — 只需提供 API Key 即可使用',
      envKey: 'ALI_API_KEY',
      availableModels: [
        { id: 'wan2.7-i2v', name: '万相 2.7 I2V', tags: ['推荐', '最新'] },
        { id: 'wan2.7-t2v', name: '万相 2.7 T2V', tags: ['最新'] },
        { id: 'wan2.7-r2v', name: '万相 2.7 R2V 参考视频', tags: ['最新'] },
        { id: 'wan2.6-i2v', name: '万相 2.6 I2V' },
        { id: 'wan2.6-i2v-flash', name: '万相 2.6 I2V Flash', tags: ['快速'] },
        { id: 'wan2.5-i2v-preview', name: '万相 2.5 I2V Preview' },
        { id: 'wan2.2-i2v-plus', name: '万相 2.2 I2V Plus', tags: ['高清'] },
        { id: 'wan2.2-i2v-flash', name: '万相 2.2 I2V Flash', tags: ['快速'] },
        { id: 'wanx2.1-kf2v-plus', name: '万相 2.1 KF2V Plus' },
      ],
    },
    {
      provider: 'custom',
      name: '自定义视频接口',
      defaultBaseUrl: '',
      defaultModel: '',
      description: '自定义视频生成接口',
      envKey: 'CUSTOM_VIDEO_API_KEY',
    },
  ],
  tts: [
    {
      provider: 'minimax',
      name: 'MiniMax',
      defaultBaseUrl: 'https://api.minimax.chat',
      defaultModel: 'speech-2.8-hd',
      description: 'MiniMax 语音合成 — 只需提供 API Key 即可使用，高质量中文语音',
      envKey: 'MINIMAX_API_KEY',
      availableModels: [
        { id: 'speech-2.8-hd', name: 'Speech 2.8 HD', tags: ['推荐', '高清'] },
        { id: 'speech-2.6', name: 'Speech 2.6', tags: ['快速'] },
      ],
    },
    {
      provider: 'openai',
      name: 'OpenAI',
      defaultBaseUrl: 'https://api.openai.com/v1',
      defaultModel: 'tts-1',
      description: 'OpenAI 语音合成 — 只需提供 API Key 即可使用（海外可用）',
      envKey: 'OPENAI_API_KEY',
      availableModels: [
        { id: 'tts-1', name: 'TTS-1', tags: ['推荐'] },
        { id: 'tts-1-hd', name: 'TTS-1 HD', tags: ['高清'] },
        { id: 'gpt-4o-mini-tts', name: 'GPT-4o Mini TTS', tags: ['最新'] },
      ],
    },
    {
      provider: 'chatfire',
      name: 'Chatfire TTS',
      defaultBaseUrl: 'https://api.chatfire.site',
      defaultModel: 'speech-2.8-hd',
      description: 'Chatfire TTS 网关 — 只需提供 API Key 即可使用（MiniMax 兼容，国内可用）',
      envKey: 'CHATFIRE_API_KEY',
      availableModels: [
        { id: 'speech-2.8-hd', name: 'Speech 2.8 HD', tags: ['推荐', '高清'] },
        { id: 'speech-2.6', name: 'Speech 2.6', tags: ['快速'] },
      ],
    },
    {
      provider: 'ali',
      name: '阿里百炼 Qwen TTS',
      defaultBaseUrl: 'https://dashscope.aliyuncs.com',
      defaultModel: 'qwen3-tts-vd-2026-01-26',
      description: '阿里百炼 Qwen TTS — 只需提供 API Key 即可使用',
      envKey: 'ALI_API_KEY',
      availableModels: [
        { id: 'qwen3-tts-vd-2026-01-26', name: 'Qwen3 TTS', tags: ['推荐', '最新'] },
      ],
    },
    {
      provider: 'fish-audio',
      name: 'Fish Audio',
      defaultBaseUrl: 'https://api.fish.audio',
      defaultModel: 'fish-speech-1.5',
      description: 'Fish Audio 语音合成 — 只需提供 API Key 即可使用，支持声音克隆',
      envKey: 'FISH_AUDIO_API_KEY',
      availableModels: [
        { id: 'fish-speech-1.5', name: 'Fish Speech 1.5', tags: ['推荐', '最新'] },
      ],
    },
    {
      provider: 'custom',
      name: '自定义 TTS 接口',
      defaultBaseUrl: '',
      defaultModel: '',
      description: '自定义 TTS 接口',
      envKey: 'CUSTOM_TTS_API_KEY',
    },
  ],
}
